export const AUTH_USER_REQUEST = "AUTH_USER_REQUEST";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_ERROR = "AUTH_USER_ERROR";

export const GET_AUTH_USER_REQUEST = "GET_AUTH_USER_REQUEST";
export const GET_AUTH_USER_SUCCESS = "GET_AUTH_USER_SUCCESS";
export const GET_AUTH_USER_ERROR = "GET_AUTH_USER_ERROR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";